# spring.application.name=document-initiation-service
# Disable HTTPS verification temporarily (use HTTP)
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://auth.qssence.com/realms/authrealm/protocol/openid-connect/certs

